// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYeggXweG6PimeFNt1s61tFYgIBVzoCY',
    appId: '1:285435385012:web:dac0c2f8e7bad08cffb3e1',
    messagingSenderId: '285435385012',
    projectId: 'meet-time-25a70',
    authDomain: 'meet-time-25a70.firebaseapp.com',
    storageBucket: 'meet-time-25a70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPbSnJHU8FG99bmGC__au8tTbKyu7ySI',
    appId: '1:285435385012:android:b9ef381fdfbb30a0ffb3e1',
    messagingSenderId: '285435385012',
    projectId: 'meet-time-25a70',
    storageBucket: 'meet-time-25a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2qxOUv-J_04aH1xX1zEg8THEIGNSwBQ',
    appId: '1:285435385012:ios:fd2c38588b40a7c2ffb3e1',
    messagingSenderId: '285435385012',
    projectId: 'meet-time-25a70',
    storageBucket: 'meet-time-25a70.firebasestorage.app',
    iosBundleId: 'com.example.videoCallingSystem',
  );
}
